[package]
name = "libmumble-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "libmumble"
path = "src/lib/lib.rs"
crate-type = ["staticlib"]

[dependencies]
chrono = "0.4.41"
ipnet = "2.11.0"

[build-dependencies]
cbindgen = "0.29"
